apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: 8181-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-cont
          image: $IMAGE_NAME
          ports:
            - containerPort: 80
              protocol: TCP
