name: Build Frontend

on: push

jobs:
  build:
    name: Build frontend
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: map-app-frontend
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build and tag image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --target runner -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        if: github.ref_name == 'develop'
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG     

      - name: Install kubectl
        if: github.ref_name == 'develop' && ${{ vars.DEPLOY_ON_K8S }} == 'true'
        uses: azure/setup-kubectl@v2.0
        with:
          version: latest

      - name: Deploy to K8s
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        if: github.ref_name == 'develop' && ${{ vars.DEPLOY_ON_K8S }} == 'true'
        run: |
          aws eks update-kubeconfig --name MapApp --region eu-central-1

          cat k8s_service.tmp.yml | envsubst > k8s_service.yml
          cat k8s_service.yml

          kubectl apply -f k8s_service.yml

